force-app/main/default/objects/Farmer__c/Farmer__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <label>Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Farmer__c/fields/Farmer_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Farmer_Advisor__c</fullName>
    <label>Farmer Advisor</label>
    <referenceTo>Farmer_Advisor__c</referenceTo>
    <relationshipLabel>Farmers</relationshipLabel>
    <relationshipName>Farmers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Farmer_Advisor__c/Farmer_Advisor__c.object-meta.xml
<CustomObject>
    <label>Farmer Advisor</label>
    <nameField>
        <label>Farmer Advisor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmer Advisors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Etape__c.field-meta.xml
<CustomField>
    <fullName>Etape__c</fullName>
    <label>Etape</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Etape1</fullName>
            </value>
            <value>
                <fullName>Etape2</fullName>
            </value>
            <value>
                <fullName>Etape3</fullName>
            </value>
            <value>
                <fullName>Etape4</fullName>
            </value>
            <value>
                <fullName>Etape5</fullName>
            </value>
            <value>
                <fullName>Etape6</fullName>
            </value>
            <value>
                <fullName>Etape7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Step_Rank__c.field-meta.xml
<CustomField>
    <fullName>Step_Rank__c</fullName>
    <label>Step Rank</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Farmer_Advisor__c.field-meta.xml
<CustomField>
    <fullName>Farmer_Advisor__c</fullName>
    <label>Farmer Advisor</label>
    <referenceTo>Farmer_Advisor__c</referenceTo>
    <relationshipLabel>Plants</relationshipLabel>
    <relationshipName>Plants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Farmer__c.field-meta.xml
<CustomField>
    <fullName>Farmer__c</fullName>
    <label>Farmer</label>
    <referenceTo>Farmer__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recommandation__c/Recommandation__c.object-meta.xml
<CustomObject>
    <label>Recommandation</label>
    <nameField>
        <label>Recommandation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recommandations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommandation__c/fields/Etape__c.field-meta.xml
<CustomField>
    <fullName>Etape__c</fullName>
    <label>Etape</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Etape1,Etape2,Etape3,Etape4,Etape5,Etape6,Etape7</fullName>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>3</label>
            </value>
            <value>
                <fullName>4</fullName>
                <isActive>false</isActive>
                <label>4</label>
            </value>
            <value>
                <fullName>5</fullName>
                <isActive>false</isActive>
                <label>5</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
            <value>
                <fullName>7</fullName>
                <isActive>false</isActive>
                <label>7</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>8</label>
            </value>
            <value>
                <fullName>9</fullName>
                <isActive>false</isActive>
                <label>9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recommandation__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Recommandations</relationshipLabel>
    <relationshipName>Recommandations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectControllerTest.cls
@isTest
public class ProjectControllerTest {
	 @isTest
    public static void Test(){
        Farmer_Advisor__c farAd=new Farmer_Advisor__c(Name='Farmeradvisor1');
        insert farAd;
        Farmer__c far=new Farmer__c(Farmer_Advisor__c=farAd.Id,Name='farmer1');
        insert far;
        Plant__c plt=new Plant__c(Name='plant1',Farmer_Advisor__c=farAd.Id);
        insert plt;
        Project__c pj=new Project__c(Plant__c=plt.id,
                                     Farmer__c=far.Id,
                                     Name='projet1');
        insert pj;
        
        Note__c note=new Note__c(Name='Note1',Etape__c='etape1',Project__c=pj.Id,Step_Rank__c=1);
        insert note;
        Recommandation__c rec= new Recommandation__c(Name='recom1', Plant__c=plt.Id,Step_Rank__c=1);
        insert rec;
        System.Test.StartTest();   
        ProjectController.getFarmerProjectsByHisName(far.Name);
        ProjectController.getAllProjects();
        ProjectController.getProjectProfil(pj.Id);
        ProjectController.retrieveProjects(far.Id,pj.Id);
        ProjectController.getPlantRecom(pj.Id);
        ProjectController.getProjectNoteByStepRank(pj.Id,note.Step_Rank__c);
        ProjectController.getCurrentStep(pj.Id);
        System.Test.StopTest();
    }  
}