force-app/main/default/objects/Farmer__c/Farmer__c.object-meta.xml
<CustomObject>
    <label>Farmer</label>
    <nameField>
        <label>Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Farmer__c.field-meta.xml
<CustomField>
    <fullName>Farmer__c</fullName>
    <label>Farmer</label>
    <referenceTo>Farmer__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/projectRelatedController.cls
public with sharing class projectRelatedController {
    public projectRelatedController() {

    }
    @AuraEnabled
    public static List<Project__c> retrieveProjects(Id cultivateurId) {
        try {
            List<Farmer__c> culti=[SELECT Id, Name, (SELECT Id, Name FROM Projects__r) FROM Farmer__c WHERE Id=:cultivateurId];
            List<Project__c> projList= culti[0].Projects__r;
            return projList;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
       
    }
}