force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Note__c/fields/Step_Rank__c.field-meta.xml
<CustomField>
    <fullName>Step_Rank__c</fullName>
    <label>Step Rank</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Periodicite_Jours__c.field-meta.xml
<CustomField>
    <fullName>Periodicite_Jours__c</fullName>
    <description>Durée d&apos;une étape</description>
    <label>Periodicite (Jours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Etape_en_Cours__c.field-meta.xml
<CustomField>
    <fullName>Etape_en_Cours__c</fullName>
    <formula>IF(AND(Date_De_Semis__c &lt;= TODAY(), NOT(ISPICKVAL(Etat__c, &quot;Etude&quot;))), IF(AND(NOT(ISPICKVAL(Etat__c, &quot;Terminé&quot;)), NOT(ISPICKVAL(Etat__c, &quot;Annulé&quot;))), FLOOR((( TODAY() - Date_De_Semis__c )/ Plant__r.Periodicite_Jours__c )+1), null), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Etape en Cours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/isUpdate__c.field-meta.xml
<CustomField>
    <fullName>isUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A jour,Pas à jour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchResetProjectUpdateStatus.cls
global class BatchResetProjectUpdateStatus implements Database.Batchable<sObject> ,Schedulable{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
                SELECT Plant__r.Periodicite_Jours__c,Etape_en_Cours__c, (SELECT Step_Rank__c,Description__c FROM Notes__r)
                FROM Project__c
                WHERE isUpdate__c = TRUE
//                and id ='a057Q000000zlHdQAI'
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Project__c> projects) {
        for (Project__c proj : projects) {
            Map<Decimal, Note__c>noteEtapeMap = new Map<Decimal, Note__c>();
            for (Note__c note : proj.Notes__r) {
                noteEtapeMap.put(note.Step_Rank__c, note);
            }
            if (noteEtapeMap.containsKey(proj.Etape_en_Cours__c) && String.isBlank(noteEtapeMap.get(proj.Etape_en_Cours__c).Description__c)) {
                proj.Status__c = 'Pas à jour';
            }
            if (!noteEtapeMap.containsKey(proj.Etape_en_Cours__c) ) {
                proj.Status__c = 'Pas à jour';
            }
        }
        update projects;
    }
    global void finish(Database.BatchableContext BC) {
    }
    global static void startSch(){
        System.schedule('Reset project status when Etape change','0 0 23 * * ?', new BatchResetProjectUpdateStatus());
    }
    global static void start(){
        Database.executeBatch(new BatchResetProjectUpdateStatus());
    }
    global void execute(SchedulableContext param1) {
        BatchResetProjectUpdateStatus.start();
    }
}