force-app/main/default/objects/Note__c/Note__c.object-meta.xml
<CustomObject>
    <label>Note</label>
    <nameField>
        <label>Note Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Note__c/fields/Etape__c.field-meta.xml
<CustomField>
    <fullName>Etape__c</fullName>
    <label>Etape</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Etape1</fullName>
            </value>
            <value>
                <fullName>Etape2</fullName>
            </value>
            <value>
                <fullName>Etape3</fullName>
            </value>
            <value>
                <fullName>Etape4</fullName>
            </value>
            <value>
                <fullName>Etape5</fullName>
            </value>
            <value>
                <fullName>Etape6</fullName>
            </value>
            <value>
                <fullName>Etape7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Note__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Notes</relationshipLabel>
    <relationshipName>Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Etape_en_Cours__c.field-meta.xml
<CustomField>
    <fullName>Etape_en_Cours__c</fullName>
    <formula>IF(AND(Date_De_Semis__c &lt;= TODAY(), NOT(ISPICKVAL(Etat__c, &quot;Etude&quot;))), IF(AND(NOT(ISPICKVAL(Etat__c, &quot;Terminé&quot;)), NOT(ISPICKVAL(Etat__c, &quot;Annulé&quot;))), FLOOR((( TODAY() - Date_De_Semis__c )/ Plant__r.Periodicite_Jours__c )+1), null), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Etape en Cours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/isUpdate__c.field-meta.xml
<CustomField>
    <fullName>isUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A jour,Pas à jour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchUpdateFirstStep.cls
global class BatchUpdateFirstStep implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
         return Database.getQueryLocator([
                SELECT Id, Name, isUpdate__c, (SELECT Etape__c, Date__c FROM Notes__r WHERE Etape__c = 'Etape 0')
                FROM Project__c
                WHERE isUpdate__c = TRUE AND Etape_en_Cours__c = 0
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Project__c> projects) {
        for (Project__c proj : projects) {
            for (Note__c note : proj.Notes__r) {
                if ((Integer.valueOf(System.today()) - Integer.valueOf(Note.Date__c)) >= 7) {
                    proj.Status__c = 'Pas à jour';
                }
            }
        }
    }
    global void finish(Database.BatchableContext BC) {
    }
}